language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.4

env:
  global:
    - BBB_SECURITY_SALT=8cd8ef52e8e101574e400365b55e11a6
    - BBB_SERVER_BASE_URL=http://test-install.blindsidenetworks.com/bigbluebutton/

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then phpunit --coverage-clover build/logs/clover.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" == "nightly" ]; then phpunit; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
